version: 2
updates:
- package-ecosystem: docker
  directory: "/latest"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/latest"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
